### ISSUE TITLE
warning: remote HEAD refers to nonexistent ref, unable to checkout

### ISSUE THREAD

**Issue by vennand** [IPv6-mPvD/wireshark#1]
Unable to clone the repository:
https://github.com/IPv6-mPvD/wireshark.git

I get this error:
warning: remote HEAD refers to nonexistent ref, unable to checkout

And according to github, this is the solution:
https://help.github.com/articles/error-remote-head-refers-to-nonexistent-ref-unable-to-checkout/

**Comment by Bloody95** [comment]
Hi,

You should checkout the pvd branch after having cloned the repo.

Regards


Le 31/10/2017 14:43, vennand a écrit :

**Comment by vennand** [comment]
Thanks
